/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author kuhail
 */
public class AccountsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountsFrame
     */
    DBManager DB;
    String UserID;
    String Cat;
    String Time;
    int AdvertiseID;
    String AdvTitle;
    String AdvDetails;
    float Price;
    String Status;
    String Date;
    String Year;
    String Month;
    String Day;
    String[] columns_advertisement = new String[]{
        "AdvTitle", "AdvDetails", "Price", "AdvDateTime"
    };

    String[] columns_my_advertisment = new String[]{
        "ID", "Title", "Description", "Price", "Status", "Date"
    };

    public AccountsFrame(DBManager DB, String UserID) {
        this.setTitle("Advertisement");
        this.DB = DB;
        this.UserID = UserID;
        initComponents();
        populate_all_accounts_table();
        populate_accounts_table(UserID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_account_button = new javax.swing.JButton();
        Advertisement_tab = new javax.swing.JTabbedPane();
        Advertisements = new javax.swing.JPanel();
        search_box_Advertisment = new javax.swing.JTextField();
        Category_box = new javax.swing.JComboBox<>();
        Period_box = new javax.swing.JComboBox<>();
        Go_advertisement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Period = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accounts_table_advertisment = new javax.swing.JTable();
        My_Advertisement = new javax.swing.JPanel();
        edit_button_my_advertisment = new javax.swing.JButton();
        delete_button_my_advertisement = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        accounts_table_my_advertisment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_account_button.setText("Add Advertisement");
        add_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_account_buttonActionPerformed(evt);
            }
        });

        search_box_Advertisment.setToolTipText("Title and/or Description Search Separate by comma");

        Category_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "CAT", "HOU", "ELC", "CCA" }));
        Category_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_boxActionPerformed(evt);
            }
        });

        Period_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Life", "Last 3 Months", "Last 6 Months", "Last 12 Months" }));
        Period_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Period_boxActionPerformed(evt);
            }
        });

        Go_advertisement.setText("GO");
        Go_advertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_advertisementActionPerformed(evt);
            }
        });

        jLabel1.setText("Title, Description:");

        Category.setText("Category");

        Period.setText("Period");

        accounts_table_advertisment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AdvTitle", "AdvDetails", "Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(accounts_table_advertisment);

        javax.swing.GroupLayout AdvertisementsLayout = new javax.swing.GroupLayout(Advertisements);
        Advertisements.setLayout(AdvertisementsLayout);
        AdvertisementsLayout.setHorizontalGroup(
            AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdvertisementsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdvertisementsLayout.createSequentialGroup()
                        .addGroup(AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdvertisementsLayout.createSequentialGroup()
                                .addComponent(Category_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Period_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdvertisementsLayout.createSequentialGroup()
                                .addComponent(Category)
                                .addGap(18, 18, 18)
                                .addComponent(Period)))
                        .addGap(24, 24, 24)
                        .addGroup(AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_box_Advertisment, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Go_advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        AdvertisementsLayout.setVerticalGroup(
            AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvertisementsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Category)
                    .addComponent(Period))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvertisementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_box_Advertisment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go_advertisement)
                    .addComponent(Period_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Advertisement_tab.addTab("Advertisements", Advertisements);

        edit_button_my_advertisment.setText("Edit");
        edit_button_my_advertisment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_button_my_advertismentActionPerformed(evt);
            }
        });

        delete_button_my_advertisement.setText("Delete");
        delete_button_my_advertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button_my_advertisementActionPerformed(evt);
            }
        });

        accounts_table_my_advertisment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        accounts_table_my_advertisment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accounts_table_my_advertismentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(accounts_table_my_advertisment);

        javax.swing.GroupLayout My_AdvertisementLayout = new javax.swing.GroupLayout(My_Advertisement);
        My_Advertisement.setLayout(My_AdvertisementLayout);
        My_AdvertisementLayout.setHorizontalGroup(
            My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(My_AdvertisementLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(My_AdvertisementLayout.createSequentialGroup()
                        .addComponent(edit_button_my_advertisment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_button_my_advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        My_AdvertisementLayout.setVerticalGroup(
            My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(My_AdvertisementLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_button_my_advertisement)
                    .addComponent(edit_button_my_advertisment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Advertisement_tab.addTab("My Advertisements", My_Advertisement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_account_button)
                    .addComponent(Advertisement_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_account_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Advertisement_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_button_my_advertismentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_button_my_advertismentActionPerformed
        // TODO add your handling code here:
        EditFrame editFrame = new EditFrame(this, DB,
                AdvertiseID, AdvTitle, AdvDetails, Price, Status, Year, Month, Day, UserID);
        editFrame.setVisible(true);
    }//GEN-LAST:event_edit_button_my_advertismentActionPerformed

    private void delete_button_my_advertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button_my_advertisementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_button_my_advertisementActionPerformed

    private void Go_advertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_advertisementActionPerformed
        // TODO add your handling code here:
        //Gets text and sets it then goes to a function that will query the search

        String full_search = search_box_Advertisment.getText();
        DBtitle_description_search(full_search);

    }//GEN-LAST:event_Go_advertisementActionPerformed

    private void add_account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_account_buttonActionPerformed
        // TODO add your handling code here:
        AddAccountFrame addFrame = new AddAccountFrame(this, DB, UserID);
        addFrame.setVisible(true);
    }//GEN-LAST:event_add_account_buttonActionPerformed

    private void Category_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_boxActionPerformed
        // TODO add your handling code here:
        Cat = (String) Category_box.getSelectedItem();
        if (Cat == "ALL") {
            Cat = "%%";
        }
        Time = (String) Period_box.getSelectedItem();
        switch (Time) {
            case "Last 3 Months":
                Time = "3";
                break;
            case "Last 6 Months":
                Time = "6";
                break;
            case "Last 12 Months":
                Time = "12";
                break;
            case "Life":
                Time = "%%";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid Period", "Error", JOptionPane.ERROR_MESSAGE);
        }
        DBAdvertisementFilter(Time, Cat);

    }//GEN-LAST:event_Category_boxActionPerformed

    private void Period_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Period_boxActionPerformed
        // TODO add your handling code here:
        Time = (String) Period_box.getSelectedItem();
        switch (Time) {
            case "Last 3 Months":
                Time = "3";
                break;
            case "Last 6 Months":
                Time = "6";
                break;
            case "Last 12 Months":
                Time = "12";
                break;
            case "Life":
                Time = "%%";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid Period", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Cat = (String) Category_box.getSelectedItem();
        if (Cat == "ALL") {
            Cat = "%%";
        }
        DBAdvertisementFilter(Time, Cat);

    }//GEN-LAST:event_Period_boxActionPerformed

    private void accounts_table_my_advertismentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accounts_table_my_advertismentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) accounts_table_my_advertisment.getModel();
        int selectRowIndex = accounts_table_my_advertisment.getSelectedRow();
        AdvertiseID = (int) model.getValueAt(selectRowIndex, 0);
        AdvTitle = (String) model.getValueAt(selectRowIndex, 1);
        AdvDetails = (String) model.getValueAt(selectRowIndex, 2);
        Price = (float) model.getValueAt(selectRowIndex, 3);
        Status = (String) model.getValueAt(selectRowIndex, 4);
        Date = (String) model.getValueAt(selectRowIndex, 5);
        List<String> DateList = Arrays.asList(Date.split("-"));
        Year = DateList.get(0);
        Month = DateList.get(1);
        Day = DateList.get(2);

    }//GEN-LAST:event_accounts_table_my_advertismentMouseClicked

    //populate all query result
    public void populate_all_accounts_table() {
        Object[][] accounts_data = DB.getallAccounts();
        this.accounts_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    public void populate_accounts_table(String UserID) {
        Object[][] accounts_data = DB.getAccounts(UserID);
        this.accounts_table_my_advertisment.setModel(new DefaultTableModel(accounts_data, columns_my_advertisment));
    }

    public void DBAdvertisementFilter(String Time, String Cat) {
        Object[][] accounts_data = DB.filter(Time, Cat);
        this.accounts_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    public void DBtitle_description_search(String full_text) {
        Object[][] accounts_data = DB.title_description_search(full_text);
        this.accounts_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Advertisement_tab;
    private javax.swing.JPanel Advertisements;
    private javax.swing.JLabel Category;
    private javax.swing.JComboBox<String> Category_box;
    private javax.swing.JButton Go_advertisement;
    private javax.swing.JPanel My_Advertisement;
    private javax.swing.JLabel Period;
    private javax.swing.JComboBox<String> Period_box;
    private javax.swing.JTable accounts_table_advertisment;
    private javax.swing.JTable accounts_table_my_advertisment;
    private javax.swing.JButton add_account_button;
    private javax.swing.JButton delete_button_my_advertisement;
    private javax.swing.JButton edit_button_my_advertisment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search_box_Advertisment;
    // End of variables declaration//GEN-END:variables
}
