/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.DBManager.Record;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 * @author kuhail
 */
public class AddAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAccountFrame
     */
    DBManager DB;
    String employee_id;
    AccountsFrame parent;

    public AddAccountFrame(AccountsFrame parent, DBManager DB, String employee_id) {
        this.setTitle("Add Frame");
        this.parent = parent;
        this.DB = DB;
        this.employee_id = employee_id;
        initComponents();
        populate_account_types();
    }

    private void populate_account_types() {
        LinkedList<Record> account_types = DB.getAccountTypes();
        this.Category_Add.removeAllItems();
        for (Record account_type : account_types) {
            this.Category_Add.addItem(account_type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Details = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        add_advertisement = new javax.swing.JButton();
        AdvTitle = new javax.swing.JTextField();
        price_box = new javax.swing.JTextField();
        Category_Add = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setText("Title:");

        Details.setText("Details:");

        Category.setText("Category");

        Price.setText("Price");

        add_advertisement.setText("Add Advertisement");
        add_advertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_advertisementActionPerformed(evt);
            }
        });

        Category_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_AddActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(add_advertisement))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Price)
                                    .addComponent(Category))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(price_box)
                                    .addComponent(Category_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Details)
                                    .addComponent(Title))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdvTitle)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(AdvTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Details)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category)
                    .addComponent(Category_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(price_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_advertisement)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_advertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_advertisementActionPerformed
        // TODO add your handling code here:
        String customer_id = this.AdvTitle.getText();
        String status = this.Category_Add.getSelectedItem().toString();
        String branch_id = this.price_box.getText();
        String type_id = ((Record) this.Category_Add.getSelectedItem()).ID;
        if (customer_id.trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Customer ID is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean result = DB.addAccount(customer_id, status, branch_id, employee_id, type_id);
        if (result) {
            JOptionPane.showMessageDialog(this,
                    "A new account was added correctly",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.populate_accounts_table();
        }
    }//GEN-LAST:event_add_advertisementActionPerformed

    private void Category_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_AddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdvTitle;
    private javax.swing.JLabel Category;
    private javax.swing.JComboBox Category_Add;
    private javax.swing.JLabel Details;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Title;
    private javax.swing.JButton add_advertisement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField price_box;
    // End of variables declaration//GEN-END:variables
}
