/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.DBManager.Record;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 * @author kuhail
 */
public class AddAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAccountFrame
     */
    DBManager DB;
    String UserID;
    AccountsFrame parent;
    float Price_Frame;

    public AddAccountFrame(AccountsFrame parent, DBManager DB, String UserID) {
        this.setTitle("Add Advertisement");
        this.parent = parent;
        this.DB = DB;
        this.UserID = parent.UserID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Details = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        add_advertisement = new javax.swing.JButton();
        AdvTitle = new javax.swing.JTextField();
        price_box = new javax.swing.JTextField();
        Category_Add = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Details_box = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Title.setText("Title:");

        Details.setText("Details:");

        Category.setText("Category");

        Price.setText("Price");

        add_advertisement.setText("Add Advertisement");
        add_advertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_advertisementActionPerformed(evt);
            }
        });

        Category_Add.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAT", "HOU", "ELC", "CCA" }));

        Details_box.setColumns(20);
        Details_box.setRows(5);
        jScrollPane1.setViewportView(Details_box);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(add_advertisement))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Price)
                                    .addComponent(Category))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(price_box)
                                    .addComponent(Category_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Details)
                                    .addComponent(Title))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdvTitle)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(AdvTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Details)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category)
                    .addComponent(Category_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(price_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_advertisement)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_advertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_advertisementActionPerformed
        // TODO add your handling code here:
        String AdvTitle = this.AdvTitle.getText().trim();
        String AdvDetails = this.Details_box.getText().trim();
        String Category = this.Category_Add.getSelectedItem().toString().trim();

        if (price_box.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Price is empty. Enter a number",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            float Price_t = Float.valueOf(this.price_box.getText().trim()).floatValue();
            if (Price_t < 0) {
                JOptionPane.showMessageDialog(this,
                        "Price should be positive",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            Price_Frame = Price_t;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Price isn't a number",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (AdvTitle.trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "AdvTitle is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (AdvDetails.trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "AdvDetails is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean result = DB.addAccount(AdvTitle, AdvDetails, Price_Frame, UserID, Category);
        if (result) {
            JOptionPane.showMessageDialog(this,
                    "A new advertisement was added correctly",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.populate_all_accounts_table();
            parent.populate_accounts_table(UserID);
        }
    }//GEN-LAST:event_add_advertisementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdvTitle;
    private javax.swing.JLabel Category;
    private javax.swing.JComboBox Category_Add;
    private javax.swing.JLabel Details;
    private javax.swing.JTextArea Details_box;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Title;
    private javax.swing.JButton add_advertisement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price_box;
    // End of variables declaration//GEN-END:variables
}
