/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author kuhail
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    DBManager DB;

    public LoginFrame(DBManager DB) {
        this.setTitle("Login");
        this.DB = DB;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserID_Box = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        Select_User = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("UserID:");

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        Select_User.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Users", "Moderator" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(UserID_Box)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Select_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserID_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(login_button)
                .addGap(18, 18, 18)
                .addComponent(Select_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String text = this.UserID_Box.getText();
        String User_type = (String) Select_User.getSelectedItem();
        if (User_type == "Users") {
            boolean result = DB.checkUser(text);
            if (!result) {
                JOptionPane.showMessageDialog(this,
                        "Invalid UserID Does Not Exist. Please Double Check Spelling.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                AccountsFrame accountsFrame = new AccountsFrame(DB, text);
                accountsFrame.setLocationRelativeTo(null);
                accountsFrame.setVisible(true);
                this.setVisible(false);
            }
        }
        if (User_type == "Moderator") {
            boolean result = DB.checkMod(text);
            if (!result) {
                JOptionPane.showMessageDialog(this,
                        "Invalid Moderator ID Does Not Exist. Please Double Check Spelling or Change Options.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                ModFrame modFrame = new ModFrame(DB, text);
                modFrame.setLocationRelativeTo(null);
                modFrame.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Select_User;
    private javax.swing.JTextField UserID_Box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login_button;
    // End of variables declaration//GEN-END:variables
}
