/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author kuhail
 */
public class ModFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountsFrame
     */
    DBManager DB;
    String UserID;
    String Cat;
    String Time;
    int AdvertiseID;
    String AdvTitle;
    String AdvDetails;
    float Price;
    String Status;
    String Date;
    String Username;
    String Year;
    String Month;
    String Day;
    boolean onclick = false;
    boolean my_onclick = false;
    String[] columns_advertisement = new String[]{
        "ID", "Title", "Description", "Price", "Date", "Username"
    };

    String[] columns_my_advertisment = new String[]{
        "ID", "Title", "Description", "Price", "Status", "Date", "Username"
    };

    public ModFrame(DBManager DB, String UserID) {
        this.setTitle("Moderator" + UserID);
        this.DB = DB;
        this.UserID = UserID;
        initComponents();
        populate_unclaim_ads();
        populate_my_mod_table(UserID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mod_Tab = new javax.swing.JTabbedPane();
        Unclaim_AD = new javax.swing.JPanel();
        search_box_Advertisment = new javax.swing.JTextField();
        Category_box = new javax.swing.JComboBox<>();
        Period_box = new javax.swing.JComboBox<>();
        Go_advertisement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Period = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mod_table_advertisment = new javax.swing.JTable();
        Claim = new javax.swing.JButton();
        My_Advertisement = new javax.swing.JPanel();
        Approve = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mod_my_advertisement = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search_box_Advertisment.setToolTipText("Title and/or Description Search Separate by comma");

        Category_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "CAT", "HOU", "ELC", "CCA" }));
        Category_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_boxActionPerformed(evt);
            }
        });

        Period_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Life", "Last 3 Months", "Last 6 Months", "Last 12 Months" }));
        Period_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Period_boxActionPerformed(evt);
            }
        });

        Go_advertisement.setText("GO");
        Go_advertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_advertisementActionPerformed(evt);
            }
        });

        jLabel1.setText("Title, Description:");

        Category.setText("Category");

        Period.setText("Period");

        mod_table_advertisment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Date", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mod_table_advertisment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mod_table_advertismentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mod_table_advertisment);

        Claim.setText("Claim AD");
        Claim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Unclaim_ADLayout = new javax.swing.GroupLayout(Unclaim_AD);
        Unclaim_AD.setLayout(Unclaim_ADLayout);
        Unclaim_ADLayout.setHorizontalGroup(
            Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Unclaim_ADLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Unclaim_ADLayout.createSequentialGroup()
                        .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Unclaim_ADLayout.createSequentialGroup()
                                .addComponent(Category_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Period_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Unclaim_ADLayout.createSequentialGroup()
                                .addComponent(Category)
                                .addGap(18, 18, 18)
                                .addComponent(Period)))
                        .addGap(24, 24, 24)
                        .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_box_Advertisment, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Go_advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Unclaim_ADLayout.createSequentialGroup()
                        .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Claim)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        Unclaim_ADLayout.setVerticalGroup(
            Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Unclaim_ADLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Category)
                    .addComponent(Period))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Unclaim_ADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_box_Advertisment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go_advertisement)
                    .addComponent(Period_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Claim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        Mod_Tab.addTab("Unclaimed Advertisments", Unclaim_AD);

        Approve.setText("Approve");
        Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveActionPerformed(evt);
            }
        });

        mod_my_advertisement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mod_my_advertisement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mod_my_advertisementMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mod_my_advertisement);

        javax.swing.GroupLayout My_AdvertisementLayout = new javax.swing.GroupLayout(My_Advertisement);
        My_Advertisement.setLayout(My_AdvertisementLayout);
        My_AdvertisementLayout.setHorizontalGroup(
            My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(My_AdvertisementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Approve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        My_AdvertisementLayout.setVerticalGroup(
            My_AdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(My_AdvertisementLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Approve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Mod_Tab.addTab("My Advertisements", My_Advertisement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Mod_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mod_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Go_advertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_advertisementActionPerformed
        // TODO add your handling code here:
        //Gets text and sets it then goes to a function that will query the search

        String full_search = search_box_Advertisment.getText();
        DBtitle_description_search(full_search);

    }//GEN-LAST:event_Go_advertisementActionPerformed

    private void Category_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_boxActionPerformed
        // TODO add your handling code here:
        Cat = (String) Category_box.getSelectedItem();
        if (Cat == "ALL") {
            Cat = "%%";
        }
        Time = (String) Period_box.getSelectedItem();
        switch (Time) {
            case "Last 3 Months":
                Time = "3";
                break;
            case "Last 6 Months":
                Time = "6";
                break;
            case "Last 12 Months":
                Time = "12";
                break;
            case "Life":
                Time = "%%";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid Period", "Error", JOptionPane.ERROR_MESSAGE);
        }
        DBAdvertisementFilter(Time, Cat, UserID);

    }//GEN-LAST:event_Category_boxActionPerformed

    private void Period_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Period_boxActionPerformed
        // TODO add your handling code here:
        Time = (String) Period_box.getSelectedItem();
        switch (Time) {
            case "Last 3 Months":
                Time = "3";
                break;
            case "Last 6 Months":
                Time = "6";
                break;
            case "Last 12 Months":
                Time = "12";
                break;
            case "Life":
                Time = "%%";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid Period", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Cat = (String) Category_box.getSelectedItem();
        if (Cat == "ALL") {
            Cat = "%%";
        }
        DBAdvertisementFilter(Time, Cat, UserID);

    }//GEN-LAST:event_Period_boxActionPerformed

    private void mod_my_advertisementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mod_my_advertisementMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) mod_my_advertisement.getModel();
        int selectRowIndex = mod_my_advertisement.getSelectedRow();
        AdvertiseID = (int) model.getValueAt(selectRowIndex, 0);
        AdvTitle = (String) model.getValueAt(selectRowIndex, 1);
        AdvDetails = (String) model.getValueAt(selectRowIndex, 2);
        Price = (float) model.getValueAt(selectRowIndex, 3);
        Status = (String) model.getValueAt(selectRowIndex, 4);
        Date = (String) model.getValueAt(selectRowIndex, 5);
        Username = (String) model.getValueAt(selectRowIndex, 6);
        List<String> DateList = Arrays.asList(Date.split("-"));
        Year = DateList.get(0);
        Month = DateList.get(1);
        Day = DateList.get(2);

    }//GEN-LAST:event_mod_my_advertisementMouseClicked

    private void mod_table_advertismentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mod_table_advertismentMouseClicked
        // TODO add your handling code here:
        onclick = true;
        DefaultTableModel model = (DefaultTableModel) mod_table_advertisment.getModel();
        int selectRowIndex = mod_table_advertisment.getSelectedRow();
        AdvertiseID = (int) model.getValueAt(selectRowIndex, 0);
        AdvTitle = (String) model.getValueAt(selectRowIndex, 1);
        AdvDetails = (String) model.getValueAt(selectRowIndex, 2);
        Price = (float) model.getValueAt(selectRowIndex, 3);
        Date = (String) model.getValueAt(selectRowIndex, 4);
        List<String> DateList = Arrays.asList(Date.split("-"));
        Year = DateList.get(0);
        Month = DateList.get(1);
        Day = DateList.get(2);
    }//GEN-LAST:event_mod_table_advertismentMouseClicked

    private void ApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveActionPerformed
        // TODO add your handling code here:
        boolean result = DB.changeAccountStatus(Status, AdvertiseID, UserID);
        if (result) {
            JOptionPane.showMessageDialog(this,
                    "Changes was made successful",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            refresh();
        }
    }//GEN-LAST:event_ApproveActionPerformed

    private void ClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaimActionPerformed
        // TODO add your handling code here:
        if (onclick == false) {
            JOptionPane.showMessageDialog(this,
                    "Select Something First",
                    "Error",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (onclick == true) {
            boolean result = DB.mod_claim(UserID, AdvertiseID);
            if (result) {
                JOptionPane.showMessageDialog(this,
                        "Claim was made successful",
                        "Confirmation",
                        JOptionPane.INFORMATION_MESSAGE);
                refresh();

            }
            onclick = false;
        }

    }//GEN-LAST:event_ClaimActionPerformed

    //populate all query result
    public void populate_unclaim_ads() {
        Object[][] accounts_data = DB.getUnclaimAds();
        this.mod_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    public void populate_my_mod_table(String UserID) {
        Object[][] accounts_data = DB.getModAds(UserID);
        this.mod_my_advertisement.setModel(new DefaultTableModel(accounts_data, columns_my_advertisment));
    }

    public void DBAdvertisementFilter(String Time, String Cat, String UserID) {
        Object[][] accounts_data = DB.modfilter(Time, Cat, UserID);
        this.mod_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    public void DBtitle_description_search(String full_text) {
        Object[][] accounts_data = DB.modTitle_description_search(full_text);
        this.mod_table_advertisment.setModel(new DefaultTableModel(accounts_data, columns_advertisement));
    }

    public void refresh() {
        populate_unclaim_ads();
        populate_my_mod_table(UserID);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approve;
    private javax.swing.JLabel Category;
    private javax.swing.JComboBox<String> Category_box;
    private javax.swing.JButton Claim;
    private javax.swing.JButton Go_advertisement;
    private javax.swing.JTabbedPane Mod_Tab;
    private javax.swing.JPanel My_Advertisement;
    private javax.swing.JLabel Period;
    private javax.swing.JComboBox<String> Period_box;
    private javax.swing.JPanel Unclaim_AD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mod_my_advertisement;
    private javax.swing.JTable mod_table_advertisment;
    private javax.swing.JTextField search_box_Advertisment;
    // End of variables declaration//GEN-END:variables
}
